name: mafy
description: UI LAUNCHER.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  #--UI
  cupertino_icons: ^1.0.2
  clean_calendar: ^1.1.0

  #--State managment
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  dartz: ^0.10.1
  http: ^1.1.0
  get_it: ^7.6.0
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1

  #--App
  installed_apps: ^1.3.1
  screen_brightness: ^0.2.2
  provider: ^6.0.5

  #--Data
  shared_preferences: ^2.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/day_stages/
    - assets/fonts/

  # To add custom fonts to your application,
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-VariableFont_wght.ttf
        - asset: assets/fonts/Caveat/static/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat/static/Caveat-Medium.ttf
        - asset: assets/fonts/Caveat/static/Caveat-SemiBold.ttf
        - asset: assets/fonts/Caveat/static/Caveat-Bold.ttf

    - family: Roboto_Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-VariableFont_wght.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Thin.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLight.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Light.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Medium.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBold.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Bold.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ThinItalic.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLightItalic.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-LightItalic.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Italic.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-MediumItalic.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBoldItalic.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-BoldItalic.ttf

